import type { Course, Platform, Deal, Review } from "./types";

export const platforms: Platform[] = [
  { slug: "physics-wallah", name: "Physics Wallah (PW)", color: "hsl(243 75% 59%)", description: "India's most affordable ed-tech platform by Alakh Pandey. Covers JEE, NEET, school boards, UPSC, SSC, CA, CS, MBA, coding, and more.", website: "https://www.pw.live", rating: 4.3, reviewCount: 128400 },
  { slug: "allen", name: "Allen Career Institute", color: "hsl(0 72% 51%)", description: "Legacy coaching giant from Kota. Pre-Medical, JEE, Foundation (6-10), CUET, CA, SAT/GRE via Allen Global, and Allen ACE for professional courses.", website: "https://www.allen.ac.in", rating: 4.4, reviewCount: 87200 },
  { slug: "unacademy", name: "Unacademy", color: "hsl(142 71% 45%)", description: "India's largest online learning platform. UPSC, JEE, NEET, CA, CS, CMA, CAT, CUET, CLAT, SSC, Banking, GATE, UGC NET, State PCS, K-12, and skills.", website: "https://unacademy.com", rating: 4.1, reviewCount: 95300 },
  { slug: "vedantu", name: "Vedantu", color: "hsl(25 95% 53%)", description: "Live interactive online tutoring for K-12, JEE, NEET, CUET. Features 1-to-1 sessions, SuperKids programs, coding courses, and language learning.", website: "https://www.vedantu.com", rating: 4.2, reviewCount: 42100 },
  { slug: "byjus-aakash", name: "BYJU'S Aakash", color: "hsl(210 100% 50%)", description: "Aakash's legacy classroom coaching combined with BYJU'S digital learning. NEET, JEE, Foundation, DLP study packages, and AIATS test series.", website: "https://www.aakash.ac.in", rating: 4.0, reviewCount: 63500 },
  { slug: "khan-academy", name: "Khan Academy India", color: "hsl(142 55% 49%)", description: "100% free NCERT/CBSE-aligned courses from Class 1-12. Math, Science, Computing, SAT Prep. Available in Hindi, Kannada, Marathi, and more.", website: "https://www.khanacademy.org", rating: 4.7, reviewCount: 210000 },
  { slug: "utkarsh", name: "Utkarsh Classes", color: "hsl(220 80% 50%)", description: "Rajasthan's leading coaching for UPSC, State PCS, Teaching (REET/CTET), SSC, Railways, Banking, Police, and Medical exams.", website: "https://utkarsh.com", rating: 4.2, reviewCount: 38700 },
  { slug: "drishti-ias", name: "Drishti IAS", color: "hsl(200 80% 40%)", description: "Premier UPSC and State PCS coaching by Dr. Vikas Divyakirti. Also covers CUET, Judiciary, UGC NET, SSC, and NCERT Foundation courses.", website: "https://www.drishtiias.com", rating: 4.5, reviewCount: 52300 },
  { slug: "sri-chaitanya", name: "Sri Chaitanya", color: "hsl(340 70% 50%)", description: "South India's leading coaching chain for JEE, NEET, and school education (6-12). Also runs Infinity Learn digital platform.", website: "https://www.srichaitanya.net", rating: 4.1, reviewCount: 31200 },
  { slug: "narayana", name: "Narayana Group", color: "hsl(30 80% 50%)", description: "Pan-India schooling and coaching. JEE, NEET, Foundation, IAS Academy, and digital learning via nLearn app.", website: "https://www.narayanagroup.com", rating: 4.0, reviewCount: 28900 },
  { slug: "codewithharry", name: "CodeWithHarry", color: "hsl(260 70% 55%)", description: "India's most popular programming educator. Free Sigma series, paid bootcamps for Web Dev, Python, Data Science with AI-era tools.", website: "https://codewithharry.com", rating: 4.6, reviewCount: 78500 },
  { slug: "striver", name: "Striver (TakeUForward)", color: "hsl(0 0% 15%)", description: "The gold standard for DSA & interview prep. Free A2Z Sheet (450+ problems), TUF+ premium platform, CS fundamentals, and System Design.", website: "https://takeuforward.org", rating: 4.8, reviewCount: 65200 },
  { slug: "tutedude", name: "TuteDude", color: "hsl(170 60% 45%)", description: "Affordable skill courses in Web Dev, App Dev, Data Science, AI/ML, UI/UX Design, Video Editing, Digital Marketing, and Finance.", website: "https://tutedude.com", rating: 4.0, reviewCount: 15600 },
  { slug: "career-launcher", name: "Career Launcher", color: "hsl(15 80% 50%)", description: "Veteran test-prep brand for CAT/MBA, CLAT/Law, CUET, IPMAT, and BBA entrances. Strong mentorship-driven programs.", website: "https://www.careerlauncher.com", rating: 4.1, reviewCount: 22300 },
  { slug: "adda247", name: "Adda247", color: "hsl(210 70% 45%)", description: "India's top platform for government job preparation — SSC, Banking, Railways, Defence, Teaching, and State exams.", website: "https://www.adda247.com", rating: 4.2, reviewCount: 47800 },
  { slug: "springboard-academy", name: "Springboard Academy", color: "hsl(120 60% 40%)", description: "Jaipur/Sikar legend for RAS/RPSC, UPSC IAS, Rajasthan Police SI, and Rajasthan state exams.", website: "https://springboardacademy.in", rating: 4.3, reviewCount: 12400 },
  { slug: "kalam-academy", name: "Kalam Academy", color: "hsl(45 80% 50%)", description: "Sikar/Jaipur powerhouse for Rajasthan teaching exams (1st/2nd/3rd Grade), RAS, LDC, CUET, and government jobs.", website: "https://kalamacademy.com", rating: 4.2, reviewCount: 9800 },
  { slug: "khan-global-studies", name: "Khan Global Studies (Khan Sir)", color: "hsl(350 70% 50%)", description: "Patna-based coaching for UPSC, BPSC, SSC, Railways, NDA/CDS, Police, CUET, NEET, and JEE at very low costs.", website: "https://khanglobalstudies.com", rating: 4.4, reviewCount: 56700 },
  { slug: "jk-shah", name: "J.K. Shah Classes", color: "hsl(220 50% 40%)", description: "One of India's oldest and most respected CA coaching institutes. CA Foundation, Inter, and Final.", website: "https://www.jkshahclasses.com", rating: 4.3, reviewCount: 11200 },
  { slug: "unique-academy", name: "Unique Academy", color: "hsl(280 50% 50%)", description: "Pune-based coaching for MPSC, UPSC, and Commerce exams including CS and CMA.", website: "https://uniqueacademy.co.in", rating: 4.1, reviewCount: 7600 },
];

export const courses: Course[] = [
  // ===== PHYSICS WALLAH =====
  { id: "pw-jee-01", name: "Arjuna JEE 2026 (Main + Advanced)", platform: "Physics Wallah (PW)", platformSlug: "physics-wallah", category: "Competitive", subcategory: "JEE", targetLevel: "Class 11-12", price: 5499, originalPrice: 12999, rating: 4.4, reviewCount: 18200, duration: "12 months", description: "Comprehensive JEE Main + Advanced preparation with top PW faculty. Includes DPPs, weekly tests, and doubt sessions.", features: ["Live classes", "DPPs & assignments", "Weekly mock tests", "Doubt clearing sessions", "Study material PDF"], url: "https://www.pw.live/study/batches", tags: ["JEE Main", "JEE Advanced", "Engineering"], language: "Hindi/English", mode: "Online" },
  { id: "pw-neet-01", name: "Lakshya NEET 2026", platform: "Physics Wallah (PW)", platformSlug: "physics-wallah", category: "Competitive", subcategory: "NEET", targetLevel: "Class 11-12", price: 4999, originalPrice: 11999, rating: 4.5, reviewCount: 22400, duration: "12 months", description: "Complete NEET UG preparation covering Physics, Chemistry, and Biology with animated lectures.", features: ["Live + recorded classes", "NCERT-based approach", "All India mock tests", "Mentorship program"], url: "https://www.pw.live/study/batches", tags: ["NEET", "Medical", "Biology"], language: "Hindi/English", mode: "Online" },
  { id: "pw-upsc-01", name: "UPSC Wallah Foundation 2026", platform: "Physics Wallah (PW)", platformSlug: "physics-wallah", category: "Government", subcategory: "UPSC", targetLevel: "Graduate", price: 7999, originalPrice: 19999, rating: 4.1, reviewCount: 5600, duration: "18 months", description: "Complete UPSC CSE preparation through OnlyIAS collaboration. GS Prelims + Mains + CSAT.", features: ["GS Foundation", "CSAT classes", "Answer writing practice", "Current affairs"], url: "https://www.pw.live", tags: ["UPSC", "IAS", "Civil Services"], language: "Hindi/English", mode: "Online" },
  { id: "pw-ca-01", name: "CA Wallah Foundation 2026", platform: "Physics Wallah (PW)", platformSlug: "physics-wallah", category: "Professional", subcategory: "CA", targetLevel: "Post 12th", price: 3999, originalPrice: 8999, rating: 4.0, reviewCount: 3200, duration: "8 months", description: "CA Foundation preparation covering all 4 papers with conceptual clarity.", features: ["Live classes", "Practice papers", "Mock tests", "Doubt sessions"], url: "https://www.pw.live", tags: ["CA Foundation", "Chartered Accountant"], language: "Hindi/English", mode: "Online" },
  { id: "pw-ncert-01", name: "NCERT Wallah Class 10 (CBSE)", platform: "Physics Wallah (PW)", platformSlug: "physics-wallah", category: "School", subcategory: "Board Exams", targetLevel: "Class 10", price: 2499, originalPrice: 5999, rating: 4.3, reviewCount: 15600, duration: "10 months", description: "Complete Class 10 CBSE board preparation. Science, Maths, SST, English.", features: ["Chapter-wise lectures", "NCERT solutions", "Board pattern tests", "Previous year papers"], url: "https://www.pw.live", tags: ["CBSE", "Class 10", "Board Exam"], language: "Hindi/English", mode: "Online" },
  { id: "pw-ssc-01", name: "SSC Wallah CGL 2026", platform: "Physics Wallah (PW)", platformSlug: "physics-wallah", category: "Government", subcategory: "SSC", targetLevel: "Graduate", price: 3499, originalPrice: 7999, rating: 4.1, reviewCount: 8900, duration: "8 months", description: "SSC CGL Tier 1 + Tier 2 complete preparation with GK, Reasoning, Quant, and English.", features: ["Full syllabus", "Daily quizzes", "Mock tests", "Current affairs"], url: "https://www.pw.live", tags: ["SSC CGL", "Government Job"], language: "Hindi", mode: "Online" },
  { id: "pw-cuet-01", name: "CUET Wallah 2026", platform: "Physics Wallah (PW)", platformSlug: "physics-wallah", category: "Competitive", subcategory: "CUET", targetLevel: "Class 12", price: 2999, originalPrice: 6999, rating: 4.2, reviewCount: 7800, duration: "6 months", description: "CUET UG preparation for Language, Domain, and General Test sections.", features: ["Domain subjects", "General Test prep", "Mock tests", "Doubt sessions"], url: "https://www.pw.live", tags: ["CUET", "University Entrance"], language: "Hindi/English", mode: "Online" },
  { id: "pw-skills-01", name: "PW Skills Full Stack Web Development", platform: "Physics Wallah (PW)", platformSlug: "physics-wallah", category: "Skills", subcategory: "Programming", targetLevel: "Beginner", price: 3999, originalPrice: 8999, rating: 4.0, reviewCount: 4500, duration: "6 months", description: "Learn HTML, CSS, JavaScript, React, Node.js, and build real projects.", features: ["Live + recorded", "Projects", "Certificate", "Placement assistance"], url: "https://pwskills.com", tags: ["Web Dev", "Coding", "Full Stack"], language: "Hindi/English", mode: "Online" },
  { id: "pw-foundation-01", name: "PW Little Champs Class 8", platform: "Physics Wallah (PW)", platformSlug: "physics-wallah", category: "School", subcategory: "Foundation", targetLevel: "Class 8", price: 1999, originalPrice: 4999, rating: 4.2, reviewCount: 6700, duration: "10 months", description: "Foundation building for Class 8 students in Maths and Science.", features: ["Animated lectures", "Worksheets", "Olympiad prep", "NTSE basics"], url: "https://www.pw.live", tags: ["Foundation", "Class 8", "Olympiad"], language: "Hindi/English", mode: "Online" },
  { id: "pw-gate-01", name: "GATE Wallah CS 2026", platform: "Physics Wallah (PW)", platformSlug: "physics-wallah", category: "Competitive", subcategory: "GATE", targetLevel: "Engineering Graduate", price: 4999, originalPrice: 10999, rating: 4.1, reviewCount: 3400, duration: "10 months", description: "GATE Computer Science complete preparation with theory + problem solving.", features: ["Full syllabus", "Previous year analysis", "Mock tests", "Mentorship"], url: "https://www.pw.live", tags: ["GATE", "CS", "Engineering"], language: "English", mode: "Online" },

  // ===== ALLEN =====
  { id: "allen-jee-01", name: "Allen Nurture JEE 2026 (2-Year)", platform: "Allen Career Institute", platformSlug: "allen", category: "Competitive", subcategory: "JEE", targetLevel: "Class 11", price: 185000, originalPrice: 210000, rating: 4.5, reviewCount: 12300, duration: "24 months", description: "Allen's flagship 2-year integrated JEE Main + Advanced program from Kota.", features: ["Classroom + online", "DLP material", "All India Test Series", "Doubt counters", "Hostel facility"], url: "https://www.allen.ac.in", tags: ["JEE Advanced", "Kota", "Engineering"], language: "English/Hindi", mode: "Hybrid" },
  { id: "allen-neet-01", name: "Allen Enthusiast NEET 2026", platform: "Allen Career Institute", platformSlug: "allen", category: "Competitive", subcategory: "NEET", targetLevel: "Class 12", price: 155000, originalPrice: 175000, rating: 4.6, reviewCount: 15700, duration: "12 months", description: "1-year NEET preparation for Class 12 students at Allen Kota.", features: ["Expert faculty", "AITS", "Study material", "Regular tests", "Performance tracking"], url: "https://www.allen.ac.in", tags: ["NEET", "Medical", "Kota"], language: "English/Hindi", mode: "Offline" },
  { id: "allen-dlp-01", name: "Allen DLP JEE Main + Advanced", platform: "Allen Career Institute", platformSlug: "allen", category: "Competitive", subcategory: "JEE", targetLevel: "Class 11-12", price: 28000, originalPrice: 35000, rating: 4.3, reviewCount: 8900, duration: "12 months", description: "Allen's Distance Learning Program — study material and All India Test Series for JEE.", features: ["Printed study material", "AITS test series", "Performance analysis", "Solutions booklet"], url: "https://www.allen.ac.in", tags: ["JEE", "DLP", "Self Study"], language: "English", mode: "Online" },
  { id: "allen-foundation-01", name: "Allen PNCF Class 9-10 Foundation", platform: "Allen Career Institute", platformSlug: "allen", category: "School", subcategory: "Foundation", targetLevel: "Class 9-10", price: 95000, originalPrice: 120000, rating: 4.4, reviewCount: 6200, duration: "24 months", description: "Pre-Nurture & Career Foundation for Class 9-10. Prepares for NTSE, Olympiads, and JEE/NEET foundation.", features: ["Olympiad coaching", "NTSE prep", "Board exam support", "Regular testing"], url: "https://www.allen.ac.in", tags: ["Foundation", "NTSE", "Olympiad"], language: "English/Hindi", mode: "Offline" },
  { id: "allen-cuet-01", name: "Allen ACE CUET 2026", platform: "Allen Career Institute", platformSlug: "allen", category: "Competitive", subcategory: "CUET", targetLevel: "Class 12", price: 35000, originalPrice: 45000, rating: 4.2, reviewCount: 3400, duration: "6 months", description: "Allen ACE division's CUET prep for Science, Commerce, and Humanities.", features: ["Domain subjects", "General Test", "Language", "Mock tests"], url: "https://www.allen.ac.in", tags: ["CUET", "University Entrance"], language: "English/Hindi", mode: "Hybrid" },
  { id: "allen-ca-01", name: "Allen ACE CA Foundation", platform: "Allen Career Institute", platformSlug: "allen", category: "Professional", subcategory: "CA", targetLevel: "Post 12th", price: 42000, originalPrice: 55000, rating: 4.1, reviewCount: 2100, duration: "8 months", description: "CA Foundation coaching by Allen ACE with focus on all 4 papers.", features: ["Expert CA faculty", "Practice sets", "Mock exams", "Doubt sessions"], url: "https://www.allen.ac.in", tags: ["CA Foundation", "Commerce"], language: "English/Hindi", mode: "Hybrid" },
  { id: "allen-sat-01", name: "Allen Global SAT Prep", platform: "Allen Career Institute", platformSlug: "allen", category: "Competitive", subcategory: "Study Abroad", targetLevel: "Class 11-12", price: 65000, originalPrice: 85000, rating: 4.3, reviewCount: 1800, duration: "6 months", description: "Digital SAT preparation by Allen Global division for students targeting US universities.", features: ["SAT Math & English", "Practice tests", "College counseling", "Score guarantee"], url: "https://www.allen.ac.in", tags: ["SAT", "Study Abroad", "USA"], language: "English", mode: "Online" },

  // ===== UNACADEMY =====
  { id: "una-upsc-01", name: "Unacademy UPSC CSE Foundation 2026", platform: "Unacademy", platformSlug: "unacademy", category: "Government", subcategory: "UPSC", targetLevel: "Graduate", price: 34999, originalPrice: 54999, rating: 4.3, reviewCount: 14200, duration: "18 months", description: "Complete UPSC CSE preparation with top educators like Roman Saini and Lukmaan IAS.", features: ["Live classes", "Test series", "Mentorship", "Answer writing", "Interview guidance"], url: "https://unacademy.com", tags: ["UPSC", "IAS", "Civil Services"], language: "Hindi/English", mode: "Online" },
  { id: "una-jee-01", name: "Unacademy JEE Nexus Elite 2026", platform: "Unacademy", platformSlug: "unacademy", category: "Competitive", subcategory: "JEE", targetLevel: "Class 11-12", price: 29999, originalPrice: 49999, rating: 4.2, reviewCount: 9800, duration: "12 months", description: "Premium JEE batch with structured learning path, weekly tests, and expert mentorship.", features: ["Top IITian faculty", "Structured schedule", "Weekly tests", "Doubt clearing", "DPPs"], url: "https://unacademy.com", tags: ["JEE Main", "JEE Advanced"], language: "English/Hindi", mode: "Online" },
  { id: "una-neet-01", name: "Unacademy NEET Plus 2026", platform: "Unacademy", platformSlug: "unacademy", category: "Competitive", subcategory: "NEET", targetLevel: "Class 11-12", price: 27999, originalPrice: 44999, rating: 4.2, reviewCount: 11500, duration: "12 months", description: "Comprehensive NEET preparation with structured batches and NCERT-first approach.", features: ["Live classes", "Test series", "Previous year analysis", "Mentorship"], url: "https://unacademy.com", tags: ["NEET", "Medical"], language: "Hindi/English", mode: "Online" },
  { id: "una-cat-01", name: "Unacademy CAT 2026 Complete", platform: "Unacademy", platformSlug: "unacademy", category: "Competitive", subcategory: "MBA", targetLevel: "Graduate", price: 19999, originalPrice: 34999, rating: 4.1, reviewCount: 5600, duration: "10 months", description: "CAT + OMETs (XAT, SNAP, NMAT, CMAT) preparation with sectional mastery.", features: ["QA, VARC, DILR", "Mock tests", "GD-PI prep", "OMETs coverage"], url: "https://unacademy.com", tags: ["CAT", "MBA", "Management"], language: "English", mode: "Online" },
  { id: "una-ssc-01", name: "Unacademy SSC CGL 2026", platform: "Unacademy", platformSlug: "unacademy", category: "Government", subcategory: "SSC", targetLevel: "Graduate", price: 9999, originalPrice: 19999, rating: 4.0, reviewCount: 7800, duration: "8 months", description: "SSC CGL complete preparation with Tier 1 + Tier 2 coverage.", features: ["Full syllabus", "Daily tests", "Current affairs", "Mock tests"], url: "https://unacademy.com", tags: ["SSC CGL", "Government Job"], language: "Hindi", mode: "Online" },
  { id: "una-ca-01", name: "Unacademy CA Intermediate Sankalp", platform: "Unacademy", platformSlug: "unacademy", category: "Professional", subcategory: "CA", targetLevel: "CA Inter", price: 24999, originalPrice: 39999, rating: 4.0, reviewCount: 2800, duration: "12 months", description: "CA Intermediate preparation covering all papers with expert CA faculty.", features: ["Group 1 & 2", "Practice papers", "RTP coverage", "Past paper analysis"], url: "https://unacademy.com", tags: ["CA Inter", "Chartered Accountant"], language: "English/Hindi", mode: "Online" },
  { id: "una-gate-01", name: "Unacademy GATE CSE 2026", platform: "Unacademy", platformSlug: "unacademy", category: "Competitive", subcategory: "GATE", targetLevel: "Engineering Graduate", price: 14999, originalPrice: 29999, rating: 4.1, reviewCount: 4200, duration: "10 months", description: "GATE Computer Science & IT preparation with subject-wise mastery.", features: ["Core CS subjects", "Previous year papers", "Mock tests", "PSU prep"], url: "https://unacademy.com", tags: ["GATE", "CS", "PSU"], language: "English", mode: "Online" },
  { id: "una-clat-01", name: "Unacademy CLAT 2026", platform: "Unacademy", platformSlug: "unacademy", category: "Competitive", subcategory: "Law", targetLevel: "Class 12", price: 14999, originalPrice: 24999, rating: 4.0, reviewCount: 3100, duration: "8 months", description: "CLAT + AILET comprehensive preparation for NLU admissions.", features: ["Legal reasoning", "English", "GK & current affairs", "Logical reasoning", "Mock tests"], url: "https://unacademy.com", tags: ["CLAT", "Law", "NLU"], language: "English", mode: "Online" },

  // ===== VEDANTU =====
  { id: "ved-jee-01", name: "Vedantu JEE Pro Plus 2026", platform: "Vedantu", platformSlug: "vedantu", category: "Competitive", subcategory: "JEE", targetLevel: "Class 11-12", price: 24999, originalPrice: 44999, rating: 4.2, reviewCount: 6700, duration: "12 months", description: "Live interactive JEE preparation with personalized attention and Eklavya track.", features: ["Live classes", "1-on-1 doubts", "Test series", "Personalized study plan"], url: "https://www.vedantu.com", tags: ["JEE Main", "JEE Advanced"], language: "English", mode: "Online" },
  { id: "ved-neet-01", name: "Vedantu Sanjivani NEET 2026", platform: "Vedantu", platformSlug: "vedantu", category: "Competitive", subcategory: "NEET", targetLevel: "Class 11-12", price: 22999, originalPrice: 39999, rating: 4.3, reviewCount: 7800, duration: "12 months", description: "Sanjivani batch — Vedantu's flagship NEET program with 4 revision cycles.", features: ["Live classes", "NCERT mastery", "Mock tests", "Faculty interaction"], url: "https://www.vedantu.com", tags: ["NEET", "Medical"], language: "English/Hindi", mode: "Online" },
  { id: "ved-cbse-01", name: "Vedantu Pro Course Class 12 CBSE", platform: "Vedantu", platformSlug: "vedantu", category: "School", subcategory: "Board Exams", targetLevel: "Class 12", price: 14999, originalPrice: 29999, rating: 4.1, reviewCount: 5200, duration: "10 months", description: "Complete Class 12 CBSE preparation for Science stream — PCM/PCB.", features: ["Live classes", "Board pattern tests", "NCERT solutions", "Doubt sessions"], url: "https://www.vedantu.com", tags: ["CBSE", "Class 12", "Board Exam"], language: "English", mode: "Online" },
  { id: "ved-supercoder-01", name: "Vedantu SuperCoders (Grade 6-8)", platform: "Vedantu", platformSlug: "vedantu", category: "Skills", subcategory: "Programming", targetLevel: "Class 6-8", price: 9999, originalPrice: 19999, rating: 4.0, reviewCount: 2100, duration: "6 months", description: "Introduction to coding and logical thinking for young learners.", features: ["Scratch & Python", "Project-based", "Live interactive", "Certificate"], url: "https://www.vedantu.com", tags: ["Coding", "Kids", "Programming"], language: "English", mode: "Online" },

  // ===== BYJU'S AAKASH =====
  { id: "aak-neet-01", name: "Aakash NEET Repeater 2026", platform: "BYJU'S Aakash", platformSlug: "byjus-aakash", category: "Competitive", subcategory: "NEET", targetLevel: "Dropper", price: 175000, originalPrice: 200000, rating: 4.2, reviewCount: 9800, duration: "12 months", description: "Aakash's dedicated dropper batch for NEET with intensive classroom coaching.", features: ["Classroom coaching", "AIATS", "Study material", "iTutor access", "Doubt sessions"], url: "https://www.aakash.ac.in", tags: ["NEET", "Dropper", "Medical"], language: "English/Hindi", mode: "Offline" },
  { id: "aak-jee-01", name: "Aakash JEE First Step (2-Year)", platform: "BYJU'S Aakash", platformSlug: "byjus-aakash", category: "Competitive", subcategory: "JEE", targetLevel: "Class 11", price: 195000, originalPrice: 225000, rating: 4.1, reviewCount: 7400, duration: "24 months", description: "2-year classroom JEE Main + Advanced preparation starting from Class 11.", features: ["Classroom + digital", "AIATS", "Printed material", "Regular tests"], url: "https://www.aakash.ac.in", tags: ["JEE", "Engineering"], language: "English/Hindi", mode: "Hybrid" },
  { id: "aak-foundation-01", name: "Aakash Foundation Class 9-10", platform: "BYJU'S Aakash", platformSlug: "byjus-aakash", category: "School", subcategory: "Foundation", targetLevel: "Class 9-10", price: 85000, originalPrice: 105000, rating: 4.0, reviewCount: 4500, duration: "24 months", description: "Foundation program for Class 9-10 covering Boards + Olympiads + early JEE/NEET.", features: ["Board prep", "Olympiad", "NTSE", "Foundation science & math"], url: "https://www.aakash.ac.in", tags: ["Foundation", "Class 9-10"], language: "English/Hindi", mode: "Offline" },

  // ===== KHAN ACADEMY =====
  { id: "khan-math-01", name: "Khan Academy Class 10 Math (CBSE)", platform: "Khan Academy India", platformSlug: "khan-academy", category: "School", subcategory: "Board Exams", targetLevel: "Class 10", price: 0, originalPrice: 0, rating: 4.7, reviewCount: 45000, duration: "Self-paced", description: "Free, NCERT-aligned Class 10 Math covering all chapters with practice exercises.", features: ["Free forever", "Practice exercises", "Progress tracking", "Multi-language"], url: "https://www.khanacademy.org", tags: ["Free", "CBSE", "Math"], language: "Hindi/English", mode: "Online" },
  { id: "khan-science-01", name: "Khan Academy Class 12 Physics (CBSE)", platform: "Khan Academy India", platformSlug: "khan-academy", category: "School", subcategory: "Board Exams", targetLevel: "Class 12", price: 0, originalPrice: 0, rating: 4.6, reviewCount: 28000, duration: "Self-paced", description: "Free Class 12 Physics lectures and exercises aligned with NCERT.", features: ["Free", "Video lectures", "Practice problems", "Mastery system"], url: "https://www.khanacademy.org", tags: ["Free", "Physics", "CBSE"], language: "English/Hindi", mode: "Online" },
  { id: "khan-sat-01", name: "Khan Academy Official SAT Prep", platform: "Khan Academy India", platformSlug: "khan-academy", category: "Competitive", subcategory: "Study Abroad", targetLevel: "Class 11-12", price: 0, originalPrice: 0, rating: 4.8, reviewCount: 120000, duration: "Self-paced", description: "Official College Board SAT prep — the only free, authorized practice resource.", features: ["Free", "Official partnership", "Full practice tests", "Personalized plan"], url: "https://www.khanacademy.org/sat", tags: ["SAT", "Free", "Study Abroad"], language: "English", mode: "Online" },

  // ===== UTKARSH =====
  { id: "utk-ras-01", name: "Utkarsh RAS Foundation 2026", platform: "Utkarsh Classes", platformSlug: "utkarsh", category: "Government", subcategory: "State PCS", targetLevel: "Graduate", price: 14999, originalPrice: 29999, rating: 4.3, reviewCount: 8900, duration: "18 months", description: "Complete RAS/RPSC preparation with Nirmal Gehlot Sir and top Rajasthan faculty.", features: ["Prelims + Mains", "Answer writing", "Current affairs", "Mock tests"], url: "https://utkarsh.com", tags: ["RAS", "RPSC", "Rajasthan"], language: "Hindi", mode: "Online" },
  { id: "utk-reet-01", name: "Utkarsh REET Level 2 (Science/Math)", platform: "Utkarsh Classes", platformSlug: "utkarsh", category: "Government", subcategory: "Teaching", targetLevel: "Graduate", price: 5999, originalPrice: 11999, rating: 4.4, reviewCount: 12300, duration: "6 months", description: "REET Level 2 Science and Math complete preparation for teacher recruitment.", features: ["Full syllabus", "Practice sets", "Mock tests", "Previous papers"], url: "https://utkarsh.com", tags: ["REET", "Teaching", "Rajasthan"], language: "Hindi", mode: "Online" },
  { id: "utk-ssc-01", name: "Utkarsh SSC CGL Gaurav Batch 2026", platform: "Utkarsh Classes", platformSlug: "utkarsh", category: "Government", subcategory: "SSC", targetLevel: "Graduate", price: 6999, originalPrice: 14999, rating: 4.2, reviewCount: 6700, duration: "8 months", description: "SSC CGL Tier 1 + 2 complete course with quant, reasoning, English, and GK.", features: ["Full syllabus", "Daily practice", "Mock tests", "Current affairs"], url: "https://utkarsh.com", tags: ["SSC CGL", "Government Job"], language: "Hindi", mode: "Online" },

  // ===== DRISHTI IAS =====
  { id: "dri-ias-01", name: "Drishti IAS GS Foundation 2026", platform: "Drishti IAS", platformSlug: "drishti-ias", category: "Government", subcategory: "UPSC", targetLevel: "Graduate", price: 54999, originalPrice: 79999, rating: 4.5, reviewCount: 7800, duration: "18 months", description: "Comprehensive UPSC GS Foundation by Dr. Vikas Divyakirti. Prelims + Mains + Ethics + Essay.", features: ["Live + recorded", "Answer writing", "Mentorship", "Current affairs", "Test series"], url: "https://www.drishtiias.com", tags: ["UPSC", "IAS", "Civil Services"], language: "Hindi/English", mode: "Online" },
  { id: "dri-cuet-01", name: "Drishti CUET 2026 (Humanities)", platform: "Drishti IAS", platformSlug: "drishti-ias", category: "Competitive", subcategory: "CUET", targetLevel: "Class 12", price: 9999, originalPrice: 18999, rating: 4.1, reviewCount: 2100, duration: "5 months", description: "CUET preparation focusing on Humanities domain subjects and General Test.", features: ["Domain subjects", "Language prep", "General Test", "Mock tests"], url: "https://www.drishtiias.com", tags: ["CUET", "Humanities"], language: "Hindi/English", mode: "Online" },

  // ===== SRI CHAITANYA =====
  { id: "sc-jee-01", name: "Sri Chaitanya ICON JEE 2026", platform: "Sri Chaitanya", platformSlug: "sri-chaitanya", category: "Competitive", subcategory: "JEE", targetLevel: "Class 11-12", price: 165000, originalPrice: 195000, rating: 4.3, reviewCount: 5600, duration: "24 months", description: "ICON (IIT Concept Oriented Neo) — Sri Chaitanya's flagship program for Top 100 JEE ranks.", features: ["Classroom coaching", "Study material", "Regular tests", "Rank analysis"], url: "https://www.srichaitanya.net", tags: ["JEE Advanced", "Top Ranks"], language: "English", mode: "Offline" },
  { id: "sc-neet-01", name: "Sri Chaitanya MEDICON NEET 2026", platform: "Sri Chaitanya", platformSlug: "sri-chaitanya", category: "Competitive", subcategory: "NEET", targetLevel: "Class 11-12", price: 145000, originalPrice: 170000, rating: 4.2, reviewCount: 4800, duration: "12 months", description: "Standard medical entrance program with proven track record.", features: ["NEET focused", "Super 60 track", "Study material", "Hostel option"], url: "https://www.srichaitanya.net", tags: ["NEET", "Medical"], language: "English/Telugu", mode: "Offline" },
  { id: "sc-infinity-01", name: "Infinity Learn NEET 2026 (Online)", platform: "Sri Chaitanya", platformSlug: "sri-chaitanya", category: "Competitive", subcategory: "NEET", targetLevel: "Class 12", price: 12999, originalPrice: 24999, rating: 4.0, reviewCount: 3200, duration: "12 months", description: "Sri Chaitanya's online wing — live classes, tests, and performance analytics.", features: ["Live classes", "AI-based analytics", "Mock tests", "Doubt clearing"], url: "https://www.infinitylearn.com", tags: ["NEET", "Online"], language: "English", mode: "Online" },

  // ===== NARAYANA =====
  { id: "nar-jee-01", name: "Narayana CO-Spark JEE 2026", platform: "Narayana Group", platformSlug: "narayana", category: "Competitive", subcategory: "JEE", targetLevel: "Class 11-12", price: 175000, originalPrice: 200000, rating: 4.2, reviewCount: 4200, duration: "24 months", description: "Top-tier JEE Advanced batch — best students from a whole city pooled into one campus.", features: ["Elite batch", "Dedicated faculty", "Intensive testing", "Performance tracking"], url: "https://www.narayanagroup.com", tags: ["JEE Advanced", "Top Batch"], language: "English", mode: "Offline" },
  { id: "nar-neet-01", name: "Narayana RT-720 NEET 2026", platform: "Narayana Group", platformSlug: "narayana", category: "Competitive", subcategory: "NEET", targetLevel: "Class 12", price: 135000, originalPrice: 160000, rating: 4.1, reviewCount: 3800, duration: "12 months", description: "Specialized NEET-focused intensive program with 720-mark target approach.", features: ["NEET intensive", "Chapter tests", "All India mocks", "Study material"], url: "https://www.narayanagroup.com", tags: ["NEET", "Medical"], language: "English/Telugu", mode: "Offline" },

  // ===== CODEWITHHARRY =====
  { id: "cwh-web-01", name: "Ultimate Web Dev Course 2026 Edition", platform: "CodeWithHarry", platformSlug: "codewithharry", category: "Skills", subcategory: "Programming", targetLevel: "Beginner", price: 599, originalPrice: 4999, rating: 4.7, reviewCount: 18900, duration: "3 months", description: "HTML5, CSS3, Modern JS, React, Node.js, Express, MongoDB — build modern websites with AI tools.", features: ["AI-assisted coding", "Real projects", "Certificate", "Lifetime access"], url: "https://codewithharry.com", tags: ["Web Dev", "MERN", "React"], language: "Hindi", mode: "Online" },
  { id: "cwh-python-01", name: "Complete Python Bootcamp 2026", platform: "CodeWithHarry", platformSlug: "codewithharry", category: "Skills", subcategory: "Programming", targetLevel: "Beginner", price: 599, originalPrice: 3999, rating: 4.6, reviewCount: 15200, duration: "2 months", description: "Python basics to advanced — OOP, Flask, Automation, and VidSnapAI project.", features: ["Project-based", "AI tools", "Certificate", "Lifetime access"], url: "https://codewithharry.com", tags: ["Python", "Programming"], language: "Hindi", mode: "Online" },
  { id: "cwh-ds-01", name: "Ultimate Job-Ready Data Science", platform: "CodeWithHarry", platformSlug: "codewithharry", category: "Skills", subcategory: "Data Science", targetLevel: "Beginner", price: 799, originalPrice: 5999, rating: 4.5, reviewCount: 7800, duration: "4 months", description: "Python, NumPy, Pandas, Matplotlib, ML algorithms — become job-ready in data science.", features: ["Hands-on projects", "ML models", "Certificate", "Placement tips"], url: "https://codewithharry.com", tags: ["Data Science", "ML", "Python"], language: "Hindi", mode: "Online" },

  // ===== STRIVER =====
  { id: "str-tuf-01", name: "TUF+ Full Access (DSA & CS)", platform: "Striver (TakeUForward)", platformSlug: "striver", category: "Skills", subcategory: "Programming", targetLevel: "Intermediate", price: 2999, originalPrice: 5999, rating: 4.8, reviewCount: 12400, duration: "Lifetime", description: "A2Z DSA Sheet (450+ problems), interactive editor, company tracks, OS/DBMS/CN, and System Design.", features: ["450+ curated problems", "Step-by-step visualizers", "Company tracks", "CS fundamentals", "System Design"], url: "https://takeuforward.org", tags: ["DSA", "Interview Prep", "FAANG"], language: "English", mode: "Online" },

  // ===== TUTEDUDE =====
  { id: "td-flutter-01", name: "TuteDude Flutter App Development", platform: "TuteDude", platformSlug: "tutedude", category: "Skills", subcategory: "Programming", targetLevel: "Beginner", price: 999, originalPrice: 4999, rating: 4.0, reviewCount: 2100, duration: "3 months", description: "Build cross-platform mobile apps with Flutter and Dart from scratch.", features: ["Live mentorship", "Projects", "Certificate", "Doubt support"], url: "https://tutedude.com", tags: ["Flutter", "App Dev", "Mobile"], language: "English/Hindi", mode: "Online" },
  { id: "td-uiux-01", name: "TuteDude UI/UX Design Mastery", platform: "TuteDude", platformSlug: "tutedude", category: "Skills", subcategory: "Design", targetLevel: "Beginner", price: 799, originalPrice: 3999, rating: 3.9, reviewCount: 1800, duration: "2 months", description: "Learn user research, wireframing, prototyping, and Figma mastery.", features: ["Figma projects", "Portfolio building", "Certificate", "Mentorship"], url: "https://tutedude.com", tags: ["UI/UX", "Design", "Figma"], language: "English", mode: "Online" },

  // ===== ADDA247 =====
  { id: "adda-bank-01", name: "Adda247 IBPS PO 2026 Complete", platform: "Adda247", platformSlug: "adda247", category: "Government", subcategory: "Banking", targetLevel: "Graduate", price: 4999, originalPrice: 9999, rating: 4.2, reviewCount: 8900, duration: "8 months", description: "Complete IBPS PO preparation — Prelims + Mains + Interview with banking-specific focus.", features: ["Full syllabus", "Mock tests", "Current affairs", "Interview prep"], url: "https://www.adda247.com", tags: ["IBPS PO", "Banking", "Government Job"], language: "Hindi/English", mode: "Online" },
  { id: "adda-ssc-01", name: "Adda247 SSC CGL 2026 Mahapack", platform: "Adda247", platformSlug: "adda247", category: "Government", subcategory: "SSC", targetLevel: "Graduate", price: 5999, originalPrice: 12999, rating: 4.1, reviewCount: 11200, duration: "10 months", description: "SSC CGL complete course with all-in-one Mahapack covering Tier 1 + 2 + 3.", features: ["Live classes", "Test series", "E-books", "Current affairs", "Doubt sessions"], url: "https://www.adda247.com", tags: ["SSC CGL", "Government Job"], language: "Hindi", mode: "Online" },
  { id: "adda-railway-01", name: "Adda247 RRB NTPC 2026", platform: "Adda247", platformSlug: "adda247", category: "Government", subcategory: "Railways", targetLevel: "Graduate", price: 3999, originalPrice: 8999, rating: 4.0, reviewCount: 6700, duration: "6 months", description: "RRB NTPC CBT 1 + CBT 2 preparation with GK, Reasoning, and Quant.", features: ["Full syllabus", "Mock tests", "GK updates", "Practice sets"], url: "https://www.adda247.com", tags: ["Railways", "NTPC", "Government Job"], language: "Hindi", mode: "Online" },

  // ===== CAREER LAUNCHER =====
  { id: "cl-cat-01", name: "Career Launcher CAT 2026 Classroom", platform: "Career Launcher", platformSlug: "career-launcher", category: "Competitive", subcategory: "MBA", targetLevel: "Graduate", price: 45000, originalPrice: 59999, rating: 4.3, reviewCount: 5600, duration: "10 months", description: "Premium CAT preparation with classroom + online hybrid model and GD-PI mentorship.", features: ["Classroom + online", "Mock tests", "GD-PI", "Interview prep", "Mentorship"], url: "https://www.careerlauncher.com", tags: ["CAT", "MBA", "IIM"], language: "English", mode: "Hybrid" },
  { id: "cl-clat-01", name: "Career Launcher CLAT 2026", platform: "Career Launcher", platformSlug: "career-launcher", category: "Competitive", subcategory: "Law", targetLevel: "Class 12", price: 32000, originalPrice: 45000, rating: 4.2, reviewCount: 3400, duration: "8 months", description: "Comprehensive CLAT + AILET preparation by India's oldest law entrance coaching.", features: ["Legal reasoning", "English comprehension", "GK", "Mock tests", "Mentorship"], url: "https://www.careerlauncher.com", tags: ["CLAT", "Law", "NLU"], language: "English", mode: "Hybrid" },

  // ===== SPRINGBOARD ACADEMY =====
  { id: "sp-ras-01", name: "Springboard RAS Foundation 2026", platform: "Springboard Academy", platformSlug: "springboard-academy", category: "Government", subcategory: "State PCS", targetLevel: "Graduate", price: 35000, originalPrice: 50000, rating: 4.4, reviewCount: 4500, duration: "18 months", description: "The most popular RAS batch in Rajasthan. Prelims + Mains + Interview with Dileep Mahecha Sir.", features: ["Expert faculty", "Answer writing", "Test series", "Interview guidance"], url: "https://springboardacademy.in", tags: ["RAS", "RPSC", "Rajasthan"], language: "Hindi", mode: "Offline" },

  // ===== KALAM ACADEMY =====
  { id: "kal-1st-01", name: "Kalam 1st Grade Teacher 2026", platform: "Kalam Academy", platformSlug: "kalam-academy", category: "Government", subcategory: "Teaching", targetLevel: "Graduate", price: 7999, originalPrice: 14999, rating: 4.3, reviewCount: 5600, duration: "8 months", description: "1st Grade School Lecturer preparation — Paper I (GK & GS) + Paper II (Subject-specific).", features: ["Full syllabus", "Task-based tests", "Practice sets", "Previous papers"], url: "https://kalamacademy.com", tags: ["1st Grade", "Teaching", "Rajasthan"], language: "Hindi", mode: "Online" },

  // ===== KHAN SIR =====
  { id: "kgs-upsc-01", name: "Khan Sir UPSC Foundation 2026", platform: "Khan Global Studies (Khan Sir)", platformSlug: "khan-global-studies", category: "Government", subcategory: "UPSC", targetLevel: "Graduate", price: 4999, originalPrice: 9999, rating: 4.4, reviewCount: 15600, duration: "12 months", description: "Very affordable UPSC CSE Foundation by the famous Khan Sir from Patna.", features: ["Bilingual", "Prelims + Mains", "CSAT", "Current affairs"], url: "https://khanglobalstudies.com", tags: ["UPSC", "IAS", "Affordable"], language: "Hindi", mode: "Online" },
  { id: "kgs-bpsc-01", name: "Khan Sir BPSC Foundation 2026", platform: "Khan Global Studies (Khan Sir)", platformSlug: "khan-global-studies", category: "Government", subcategory: "State PCS", targetLevel: "Graduate", price: 2999, originalPrice: 5999, rating: 4.3, reviewCount: 12300, duration: "10 months", description: "BPSC Prelims + Mains at the most affordable price from Bihar's most famous educator.", features: ["Full syllabus", "Previous papers", "Mock tests", "Current affairs"], url: "https://khanglobalstudies.com", tags: ["BPSC", "Bihar", "State PCS"], language: "Hindi", mode: "Online" },

  // ===== J.K. SHAH =====
  { id: "jks-ca-01", name: "J.K. Shah CA Foundation 2026", platform: "J.K. Shah Classes", platformSlug: "jk-shah", category: "Professional", subcategory: "CA", targetLevel: "Post 12th", price: 15000, originalPrice: 22000, rating: 4.4, reviewCount: 4500, duration: "8 months", description: "India's most trusted CA coaching — Foundation level covering all 4 papers.", features: ["Expert CA faculty", "Practice papers", "Mock exams", "Doubt sessions", "Study material"], url: "https://www.jkshahclasses.com", tags: ["CA Foundation", "Chartered Accountant"], language: "English", mode: "Hybrid" },

  // ===== LIFESTYLE / KNOWLEDGE =====
  { id: "khan-prog-01", name: "Khan Academy Computer Programming", platform: "Khan Academy India", platformSlug: "khan-academy", category: "Lifestyle", subcategory: "Programming", targetLevel: "Anyone", price: 0, originalPrice: 0, rating: 4.5, reviewCount: 35000, duration: "Self-paced", description: "Free courses on JavaScript, HTML/CSS, SQL, and Pixar-in-a-Box animation science.", features: ["100% Free", "Interactive challenges", "Projects", "Self-paced"], url: "https://www.khanacademy.org", tags: ["Free", "Programming", "Fun"], language: "English", mode: "Online" },
  { id: "td-stock-01", name: "TuteDude Stock Market Course", platform: "TuteDude", platformSlug: "tutedude", category: "Lifestyle", subcategory: "Finance", targetLevel: "Anyone", price: 999, originalPrice: 3999, rating: 3.9, reviewCount: 3200, duration: "2 months", description: "Technical & fundamental analysis of the Indian stock market for beginners.", features: ["Live sessions", "Chart reading", "Real examples", "Certificate"], url: "https://tutedude.com", tags: ["Stock Market", "Finance", "Investment"], language: "Hindi/English", mode: "Online" },
  { id: "ved-english-01", name: "Vedantu Spoken English Course", platform: "Vedantu", platformSlug: "vedantu", category: "Lifestyle", subcategory: "Languages", targetLevel: "Anyone", price: 4999, originalPrice: 9999, rating: 4.0, reviewCount: 2800, duration: "3 months", description: "Improve your spoken English with live interactive sessions and practice.", features: ["Live classes", "Speaking practice", "Grammar", "Vocabulary"], url: "https://www.vedantu.com", tags: ["English", "Speaking", "Language"], language: "English", mode: "Online" },
  { id: "td-digital-01", name: "TuteDude Digital Marketing Course", platform: "TuteDude", platformSlug: "tutedude", category: "Lifestyle", subcategory: "Marketing", targetLevel: "Anyone", price: 699, originalPrice: 2999, rating: 3.8, reviewCount: 1500, duration: "2 months", description: "SEO, Social Media Marketing, Google Ads, and content strategy for beginners.", features: ["Practical projects", "Certificate", "Mentorship", "Real campaigns"], url: "https://tutedude.com", tags: ["Digital Marketing", "SEO", "Social Media"], language: "English/Hindi", mode: "Online" },

  // ===== MORE SKILL COURSES =====
  { id: "td-video-01", name: "TuteDude Video Editing (Premiere Pro)", platform: "TuteDude", platformSlug: "tutedude", category: "Skills", subcategory: "Video Editing", targetLevel: "Beginner", price: 799, originalPrice: 3999, rating: 4.0, reviewCount: 2400, duration: "2 months", description: "Learn professional video editing with Adobe Premiere Pro — from cuts to color grading.", features: ["Premiere Pro basics to advanced", "Color grading", "Transitions & effects", "Certificate"], url: "https://tutedude.com", tags: ["Video Editing", "Premiere Pro", "Creative"], language: "English/Hindi", mode: "Online" },
  { id: "td-aftereffects-01", name: "TuteDude Motion Graphics (After Effects)", platform: "TuteDude", platformSlug: "tutedude", category: "Skills", subcategory: "Video Editing", targetLevel: "Beginner", price: 899, originalPrice: 4499, rating: 3.9, reviewCount: 1600, duration: "3 months", description: "Create stunning motion graphics and VFX with Adobe After Effects.", features: ["Keyframe animation", "Visual effects", "Logo reveals", "Certificate"], url: "https://tutedude.com", tags: ["After Effects", "Motion Graphics", "VFX"], language: "English", mode: "Online" },
  { id: "td-graphic-01", name: "TuteDude Graphic Design (Photoshop + Illustrator)", platform: "TuteDude", platformSlug: "tutedude", category: "Skills", subcategory: "Design", targetLevel: "Beginner", price: 699, originalPrice: 3499, rating: 4.0, reviewCount: 2200, duration: "2 months", description: "Master Adobe Photoshop and Illustrator for social media, branding, and print design.", features: ["Photoshop mastery", "Illustrator basics", "Portfolio projects", "Certificate"], url: "https://tutedude.com", tags: ["Graphic Design", "Photoshop", "Illustrator"], language: "English/Hindi", mode: "Online" },
  { id: "cwh-nextjs-01", name: "CodeWithHarry Next.js & Tailwind", platform: "CodeWithHarry", platformSlug: "codewithharry", category: "Skills", subcategory: "Programming", targetLevel: "Intermediate", price: 0, originalPrice: 0, rating: 4.5, reviewCount: 8900, duration: "Self-paced", description: "Free YouTube playlist covering modern frontend with Next.js, Tailwind CSS, and deployment.", features: ["Free on YouTube", "Project-based", "Modern stack", "Self-paced"], url: "https://codewithharry.com", tags: ["Next.js", "Tailwind", "Frontend"], language: "Hindi", mode: "Online" },
  { id: "cwh-cyber-01", name: "CodeWithHarry Ethical Hacking Basics", platform: "CodeWithHarry", platformSlug: "codewithharry", category: "Skills", subcategory: "Cybersecurity", targetLevel: "Beginner", price: 0, originalPrice: 0, rating: 4.3, reviewCount: 5400, duration: "Self-paced", description: "Introduction to ethical hacking, penetration testing, and cybersecurity fundamentals.", features: ["Free on YouTube", "Kali Linux", "Network security", "Self-paced"], url: "https://codewithharry.com", tags: ["Ethical Hacking", "Cybersecurity", "Security"], language: "Hindi", mode: "Online" },
  { id: "pw-dsa-01", name: "PW Skills DSA with Java", platform: "Physics Wallah (PW)", platformSlug: "physics-wallah", category: "Skills", subcategory: "Programming", targetLevel: "Beginner", price: 2999, originalPrice: 6999, rating: 4.1, reviewCount: 3200, duration: "5 months", description: "Data Structures & Algorithms course in Java — from arrays to graphs and dynamic programming.", features: ["Live classes", "Assignments", "Mock interviews", "Certificate"], url: "https://pwskills.com", tags: ["DSA", "Java", "Placement"], language: "Hindi/English", mode: "Online" },
  { id: "pw-datascience-01", name: "PW Skills Data Science Masters", platform: "Physics Wallah (PW)", platformSlug: "physics-wallah", category: "Skills", subcategory: "Data Science", targetLevel: "Beginner", price: 3499, originalPrice: 7999, rating: 4.0, reviewCount: 2800, duration: "6 months", description: "End-to-end data science with Python, Stats, ML, Deep Learning, and NLP.", features: ["Live classes", "Real projects", "Certificate", "Placement support"], url: "https://pwskills.com", tags: ["Data Science", "ML", "AI"], language: "Hindi/English", mode: "Online" },
  { id: "una-python-01", name: "Unacademy Python for Beginners", platform: "Unacademy", platformSlug: "unacademy", category: "Skills", subcategory: "Programming", targetLevel: "Beginner", price: 4999, originalPrice: 9999, rating: 4.0, reviewCount: 2100, duration: "3 months", description: "Learn Python from scratch — variables, loops, OOP, file handling, and mini projects.", features: ["Live classes", "Coding exercises", "Certificate", "Doubt support"], url: "https://unacademy.com", tags: ["Python", "Programming", "Beginner"], language: "English/Hindi", mode: "Online" },
  { id: "td-powerbi-01", name: "TuteDude Power BI & Data Analytics", platform: "TuteDude", platformSlug: "tutedude", category: "Skills", subcategory: "Data Science", targetLevel: "Beginner", price: 899, originalPrice: 3999, rating: 4.0, reviewCount: 1400, duration: "2 months", description: "Data visualization and analytics with Microsoft Power BI and SQL.", features: ["Dashboard building", "SQL basics", "Real datasets", "Certificate"], url: "https://tutedude.com", tags: ["Power BI", "Analytics", "SQL"], language: "English/Hindi", mode: "Online" },
  { id: "td-react-native-01", name: "TuteDude React Native App Dev", platform: "TuteDude", platformSlug: "tutedude", category: "Skills", subcategory: "Programming", targetLevel: "Intermediate", price: 1199, originalPrice: 4999, rating: 3.9, reviewCount: 1100, duration: "3 months", description: "Build cross-platform mobile apps with React Native and deploy to Play Store & App Store.", features: ["React Native", "Real projects", "Deployment guide", "Certificate"], url: "https://tutedude.com", tags: ["React Native", "App Dev", "Mobile"], language: "English/Hindi", mode: "Online" },
];

export const deals: Deal[] = [
  { id: "d1", courseId: "pw-jee-01", title: "Summer Sale — PW JEE", discount: "58% OFF", validTill: "2026-04-30", code: "SUMMER26", tag: "Summer Sale" },
  { id: "d2", courseId: "pw-neet-01", title: "NEET Mega Offer", discount: "58% OFF", validTill: "2026-04-30", code: "NEET2026", tag: "Limited Time" },
  { id: "d3", courseId: "cwh-web-01", title: "CWH Web Dev — Flat ₹599", discount: "88% OFF", validTill: "2026-05-15", tag: "Best Seller" },
  { id: "d4", courseId: "una-upsc-01", title: "Unacademy Republic Day Sale", discount: "36% OFF", validTill: "2026-03-31", code: "REPUBLIC26", tag: "Festival Sale" },
  { id: "d5", courseId: "str-tuf-01", title: "TUF+ Lifetime Access", discount: "50% OFF", validTill: "2026-06-30", tag: "Popular" },
  { id: "d6", courseId: "ved-jee-01", title: "Vedantu Holi Bonanza", discount: "44% OFF", validTill: "2026-03-20", code: "HOLI26", tag: "Holi Sale" },
  { id: "d7", courseId: "cwh-python-01", title: "Python Bootcamp Launch Price", discount: "85% OFF", validTill: "2026-04-30", tag: "New Launch" },
  { id: "d8", courseId: "adda-bank-01", title: "Adda247 Banking Mahapack", discount: "50% OFF", validTill: "2026-03-31", code: "BANK50", tag: "Govt Job Special" },
  { id: "d9", courseId: "kgs-upsc-01", title: "Khan Sir UPSC Budget Price", discount: "50% OFF", validTill: "2026-05-31", tag: "Affordable" },
  { id: "d10", courseId: "allen-dlp-01", title: "Allen DLP Early Bird", discount: "20% OFF", validTill: "2026-04-15", code: "EARLY26", tag: "Early Bird" },
];

// MASSIVE LIST OF REALISTIC REDDIT AND USER REVIEWS
export const sampleReviews: Review[] = [
  // --- PW Arjuna JEE ---
  { id: "r1", courseId: "pw-jee-01", author: "u/aspirant_2026", rating: 4, text: "PW JEE course is genuinely good for the price. Faculty explains concepts well. Only downside is the app lags sometimes.", date: "2026-02-15", source: "reddit" },
  { id: "r2", courseId: "pw-jee-01", author: "Rahul K.", rating: 5, text: "Best value JEE course. Alakh Sir's team has improved a lot. Doubt clearing is faster now.", date: "2026-03-01", source: "user" },
  { id: "r3", courseId: "pw-jee-01", author: "u/MathGeek_01", rating: 3, text: "Maths faculty is amazing, but chemistry feels a bit rushed in the middle chapters. Still, for this price, you can't really complain.", date: "2026-02-28", source: "reddit" },
  { id: "r4", courseId: "pw-jee-01", author: "Sneha Patel", rating: 5, text: "Cleared my 11th basics perfectly. The DPPs are exactly board/mains level. Highly recommend sticking to the schedule.", date: "2026-03-10", source: "user" },
  { id: "r5", courseId: "pw-jee-01", author: "u/tired_student", rating: 3, text: "Honestly, the app crashes during live polls sometimes. Content is 10/10 but the tech side needs some serious work.", date: "2026-01-20", source: "reddit" },
  { id: "r6", courseId: "pw-jee-01", author: "Aman Gupta", rating: 4, text: "Too much spam in the live chat by kids. I recommend watching the recorded lectures on 1.5x speed.", date: "2026-03-12", source: "user" },

  // --- Allen Nurture JEE ---
  { id: "r7", courseId: "allen-jee-01", author: "u/kota_warrior", rating: 5, text: "Allen Kota is still the king for serious JEE aspirants. The environment and peer group make a huge difference.", date: "2026-01-20", source: "reddit" },
  { id: "r8", courseId: "allen-jee-01", author: "Priya S.", rating: 4, text: "Expensive but worth it if you're disciplined. Material quality is unmatched.", date: "2026-02-28", source: "user" },
  { id: "r9", courseId: "allen-jee-01", author: "u/stressed_kid", rating: 3, text: "The peer pressure here is insane. If you can handle the stress, the material is gold. If not, it can get very toxic very fast.", date: "2026-03-02", source: "reddit" },
  { id: "r10", courseId: "allen-jee-01", author: "Vikram R.", rating: 5, text: "Hostel life is tough, but the doubt counters are a lifesaver. Teachers are always available till 8 PM.", date: "2026-02-14", source: "user" },
  { id: "r11", courseId: "allen-jee-01", author: "u/jee_prep_bot", rating: 4, text: "AITS (Test Series) is way harder than actual JEE. It demotivates you sometimes, but prepares you for the worst.", date: "2026-03-05", source: "reddit" },
  { id: "r12", courseId: "allen-jee-01", author: "Rohan D.", rating: 2, text: "You only get the absolute best teachers if you are in the top star batches. Average batches get average teachers. Truth.", date: "2026-01-15", source: "user" },

  // --- CodeWithHarry Web Dev ---
  { id: "r13", courseId: "cwh-web-01", author: "u/codingbeginner", rating: 5, text: "Harry bhai ka course is literally the best for Indian beginners. Hindi explanations + practical projects = chef's kiss.", date: "2026-03-05", source: "reddit" },
  { id: "r14", courseId: "cwh-web-01", author: "Karan M.", rating: 4, text: "Awesome for basics, but the React section feels a tiny bit outdated since hooks changed. Still a solid 4/5.", date: "2026-02-22", source: "user" },
  { id: "r15", courseId: "cwh-web-01", author: "u/backend_bro", rating: 3, text: "Some of the backend Node.js videos drag on for too long. Could be a bit more concise. Good otherwise.", date: "2026-03-10", source: "reddit" },
  { id: "r16", courseId: "cwh-web-01", author: "Neha Sharma", rating: 5, text: "Got my first internship because of the eCommerce portfolio project we built here. Thank you Harry!", date: "2026-01-28", source: "user" },
  { id: "r17", courseId: "cwh-web-01", author: "u/dev_in_making", rating: 5, text: "The discord community associated with this is super helpful when you get stuck on a weird CSS bug.", date: "2026-02-18", source: "reddit" },
  { id: "r18", courseId: "cwh-web-01", author: "Amit P.", rating: 4, text: "It's free on YouTube anyway, why pay? But honestly the organized structure and certificates here make it nice.", date: "2026-03-01", source: "user" },

  // --- Unacademy UPSC ---
  { id: "r19", courseId: "una-upsc-01", author: "u/upsc_daily", rating: 3, text: "Good educators but the subscription model is confusing. Some top teachers left which affected quality recently.", date: "2026-02-10", source: "reddit" },
  { id: "r20", courseId: "una-upsc-01", author: "Ravi Teja", rating: 5, text: "Mrunal sir's economy course is unmatched. Worth the entire subscription price just for that one subject.", date: "2026-03-08", source: "user" },
  { id: "r21", courseId: "una-upsc-01", author: "u/ias_dreamer", rating: 2, text: "Way too expensive now compared to earlier years. Also, there are too many classes, it's impossible to keep up.", date: "2026-01-12", source: "reddit" },
  { id: "r22", courseId: "una-upsc-01", author: "Pooja Desai", rating: 4, text: "The platform UI is the best among all ed-tech apps in India. Very smooth experience on the iPad.", date: "2026-02-25", source: "user" },
  { id: "r23", courseId: "una-upsc-01", author: "u/mains_writer", rating: 3, text: "Answer writing evaluation takes forever sometimes. They promise 48 hours but it takes a week. Needs improvement.", date: "2026-03-11", source: "reddit" },
  { id: "r24", courseId: "una-upsc-01", author: "Aditya N.", rating: 5, text: "Cleared my prelims purely relying on their crash course and test series. Highly recommend.", date: "2026-01-05", source: "user" },

  // --- Striver TUF+ ---
  { id: "r25", courseId: "str-tuf-01", author: "u/faang_dreamer", rating: 5, text: "Striver's A2Z sheet got me into Google. TUF+ is just the premium version of something already gold.", date: "2026-01-30", source: "reddit" },
  { id: "r26", courseId: "str-tuf-01", author: "Siddharth J.", rating: 5, text: "The best DSA resource on the internet. Period. Don't waste money on 50k bootcamps.", date: "2026-03-02", source: "user" },
  { id: "r27", courseId: "str-tuf-01", author: "u/java_dev99", rating: 4, text: "Sometimes the C++ code is hard to translate if you are a strict Java guy, but the logic video explanation is flawless.", date: "2026-02-18", source: "reddit" },
  { id: "r28", courseId: "str-tuf-01", author: "Mohit S.", rating: 3, text: "System design section is a bit basic right now. Good for SDE1, but not for senior roles. Hope he updates it.", date: "2026-03-14", source: "user" },
  { id: "r29", courseId: "str-tuf-01", author: "u/leet_coder", rating: 5, text: "The new interactive platform is a game changer. No more switching between leetcode and youtube.", date: "2026-01-22", source: "reddit" },
  { id: "r30", courseId: "str-tuf-01", author: "Ananya K.", rating: 4, text: "Only downside is his accent takes a day or two to get used to, but the content is absolute top-notch.", date: "2026-02-05", source: "user" },

  // --- Drishti IAS ---
  { id: "r31", courseId: "dri-ias-01", author: "Ankit M.", rating: 5, text: "Vikas Divyakirti Sir's ethics and essay classes are worth every penny. Best UPSC coaching online.", date: "2026-02-20", source: "user" },
  { id: "r32", courseId: "dri-ias-01", author: "u/hindi_medium", rating: 5, text: "Hindi medium students have no better option than Drishti. The study material is the absolute best.", date: "2026-03-09", source: "reddit" },
  { id: "r33", courseId: "dri-ias-01", author: "Ramesh C.", rating: 3, text: "Their current affairs magazine is good but very bulky. Hard to revise at the last minute before prelims.", date: "2026-01-28", source: "user" },
  { id: "r34", courseId: "dri-ias-01", author: "u/upsc_prep", rating: 3, text: "Mentorship program is a hit or miss depending on who is assigned to you. My mentor rarely replies.", date: "2026-02-15", source: "reddit" },
  { id: "r35", courseId: "dri-ias-01", author: "Sunita Y.", rating: 4, text: "Test series is very close to actual UPSC standards. Detailed explanations provided for every question.", date: "2026-03-01", source: "user" },

  // --- Adda247 Banking ---
  { id: "r36", courseId: "adda-bank-01", author: "u/bank_babu", rating: 5, text: "Best for bank PO exams. The mock tests are exactly like the real IBPS exam UI.", date: "2026-02-25", source: "reddit" },
  { id: "r37", courseId: "adda-bank-01", author: "Prakash T.", rating: 3, text: "Quant faculty is good, but English could be a lot better. I had to read separate books for grammar.", date: "2026-03-10", source: "user" },
  { id: "r38", courseId: "adda-bank-01", author: "u/sbi_dream", rating: 5, text: "Bought the Mahapack and it covers everything. Very affordable compared to offline coaching.", date: "2026-01-15", source: "reddit" },
  { id: "r39", courseId: "adda-bank-01", author: "Meena R.", rating: 2, text: "Customer support is terrible if you face payment issues. Took them a week to activate my batch.", date: "2026-02-05", source: "user" },
  { id: "r40", courseId: "adda-bank-01", author: "u/current_affairs", rating: 5, text: "Current affairs capsule by Ashish sir is a lifesaver. Most questions in Mains came directly from his PDFs.", date: "2026-03-12", source: "reddit" },

  // --- Khan Academy Math ---
  { id: "r41", courseId: "khan-math-01", author: "u/broke_student", rating: 5, text: "I can't believe this is 100% free. Honestly better than the paid tuition I used to go to.", date: "2026-02-20", source: "reddit" },
  { id: "r42", courseId: "khan-math-01", author: "Dr. Sharma", rating: 5, text: "The mastery point system makes doing math feel like a video game. My little brother loves it.", date: "2026-03-01", source: "user" },
  { id: "r43", courseId: "khan-math-01", author: "u/bored_guy", rating: 3, text: "Voice is a bit monotonous sometimes, makes me sleepy. But the logic is clear.", date: "2026-01-25", source: "reddit" },
  { id: "r44", courseId: "khan-math-01", author: "Anita P.", rating: 4, text: "Excellent for clearing basics, but you'll need RD Sharma or RS Aggarwal for actual board prep practice.", date: "2026-03-11", source: "user" },
  { id: "r45", courseId: "khan-math-01", author: "u/hindi_learner", rating: 5, text: "The new Hindi subtitles and dubbed videos really helped me grasp the difficult trigonometry concepts.", date: "2026-02-14", source: "reddit" },

  // --- Khan Global Studies (Khan Sir) ---
  { id: "r46", courseId: "kgs-upsc-01", author: "u/patna_boy", rating: 5, text: "Khan Sir's teaching style is legendary. He uses real-life examples and you will never forget what he teaches.", date: "2026-03-05", source: "reddit" },
  { id: "r47", courseId: "kgs-upsc-01", author: "Deepak S.", rating: 5, text: "At ₹4999, you cannot get a better UPSC foundation anywhere in India. He is revolutionizing education.", date: "2026-02-18", source: "user" },
  { id: "r48", courseId: "kgs-upsc-01", author: "u/serious_aspirant", rating: 4, text: "Crowd in live chat is very non-serious. Lots of memes. I always keep the chat disabled while watching.", date: "2026-01-30", source: "reddit" },
  { id: "r49", courseId: "kgs-upsc-01", author: "Jyoti M.", rating: 3, text: "Notes are mostly in Hindi. English medium students might struggle a bit to translate technical terms.", date: "2026-03-08", source: "user" },
  { id: "r50", courseId: "kgs-upsc-01", author: "u/geo_nerd", rating: 4, text: "Geography and History are his strong points. Science & Tech is just okay, could be covered deeper.", date: "2026-02-22", source: "reddit" },

  // --- TuteDude Flutter ---
  { id: "r51", courseId: "td-flutter-01", author: "u/app_dev_noob", rating: 5, text: "Built my first play store app using this! The final clone project is very comprehensive.", date: "2026-03-12", source: "reddit" },
  { id: "r52", courseId: "td-flutter-01", author: "Kritika L.", rating: 3, text: "Projects are good, but the audio quality in the first few videos is poor. Lots of background static.", date: "2026-02-15", source: "user" },
  { id: "r53", courseId: "td-flutter-01", author: "u/stuck_in_code", rating: 4, text: "Mentorship is surprisingly decent. Got my complex state management doubts resolved within 24 hours.", date: "2026-03-01", source: "reddit" },
  { id: "r54", courseId: "td-flutter-01", author: "Varun B.", rating: 3, text: "Very basic. Good if you have zero coding knowledge, but way too slow if you already know JavaScript/Java.", date: "2026-01-20", source: "user" },
  { id: "r55", courseId: "td-flutter-01", author: "u/budget_coder", rating: 4, text: "Worth the price when bought on sale for ₹999. I wouldn't pay the full ₹4999 price though.", date: "2026-02-28", source: "reddit" }
];

export const categories = [
  { id: "school", label: "School (K-12)", icon: "📚", description: "CBSE, ICSE, State Boards, Foundation" },
  { id: "competitive", label: "Competitive Exams", icon: "🎯", description: "JEE, NEET, CUET, SAT, GATE, CAT, CLAT" },
  { id: "professional", label: "Professional Courses", icon: "💼", description: "CA, CS, CMA, MBA" },
  { id: "government", label: "Government Jobs", icon: "🏛️", description: "UPSC, SSC, Banking, Railways, Teaching, State PCS" },
  { id: "skills", label: "Skill Courses", icon: "💻", description: "Coding, DSA, Data Science, AI/ML, App Dev" },
  { id: "lifestyle", label: "Knowledge & Lifestyle", icon: "🌱", description: "Languages, Finance, Marketing, Personal Growth" },
];

export const targetLevels = [
  "Class 6-8", "Class 8", "Class 9-10", "Class 10", "Class 11", "Class 11-12", "Class 12",
  "Dropper", "Post 12th", "CA Inter", "Graduate", "Engineering Graduate", "Beginner", "Intermediate", "Anyone"
];

export const subcategories = [
  "JEE", "NEET", "CUET", "GATE", "MBA", "Law", "Study Abroad",
  "Board Exams", "Foundation",
  "CA", "CS",
  "UPSC", "SSC", "Banking", "Railways", "Teaching", "State PCS",
  "Programming", "Data Science", "Design", "Video Editing", "Cybersecurity",
  "Finance", "Languages", "Marketing",
];
